const remediation = require('./remediation');

const API_BASE = 'https://api.github.com';
const TOKEN = process.env.GITHUB_TOKEN;
const OWNER = process.env.GITHUB_OWNER;
const REPO = process.env.GITHUB_REPO;

function headers() {
  return {
    Authorization: `Bearer ${TOKEN}`,
    Accept: 'application/vnd.github+json',
    'Content-Type': 'application/json',
  };
}

async function githubRequest(path, options = {}) {
  const res = await fetch(`${API_BASE}${path}`, { ...options, headers: headers() });
  if (!res.ok) {
    const body = await res.text();
    throw new Error(`GitHub API ${options.method || 'GET'} ${path} failed: ${res.status} ${body}`);
  }
  return res.status === 204 ? null : res.json();
}

async function getDefaultBranchSha() {
  const repoInfo = await githubRequest(`/repos/${OWNER}/${REPO}`);
  const branch = repoInfo.default_branch;
  const ref = await githubRequest(`/repos/${OWNER}/${REPO}/git/ref/heads/${branch}`);
  return { branch, sha: ref.object.sha };
}

async function createBranch(branchName, fromSha) {
  await githubRequest(`/repos/${OWNER}/${REPO}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: `refs/heads/${branchName}`, sha: fromSha }),
  });
}

async function getFileContent(path, ref) {
  const data = await githubRequest(`/repos/${OWNER}/${REPO}/contents/${path}?ref=${ref}`);
  const content = Buffer.from(data.content, 'base64').toString('utf-8');
  return { content, sha: data.sha };
}

async function updateFileContent(path, newContent, message, sha, branch) {
  await githubRequest(`/repos/${OWNER}/${REPO}/contents/${path}`, {
    method: 'PUT',
    body: JSON.stringify({
      message,
      content: Buffer.from(newContent, 'utf-8').toString('base64'),
      sha,
      branch,
    }),
  });
}

async function openPullRequest(branch, baseBranch, title, body) {
  const pr = await githubRequest(`/repos/${OWNER}/${REPO}/pulls`, {
    method: 'POST',
    body: JSON.stringify({ title, body, head: branch, base: baseBranch }),
  });
  return pr.html_url;
}

function isFixableFilePath(path) {
  return Boolean(path) && !/^https?:\/\//i.test(path);
}

async function createFixPullRequest(findings) {
  if (!TOKEN || !OWNER || !REPO) {
    throw new Error('GitHub integration is not configured (GITHUB_TOKEN / GITHUB_OWNER / GITHUB_REPO missing)');
  }
  const withPath = findings.filter((f) => isFixableFilePath(f.file_path));
  if (withPath.length === 0) {
    throw new Error(
      'None of the queued findings have a fixable file path (DAST findings point at a URL, not a file, so they can\'t be turned into a code fix)'
    );
  }

  const { branch: baseBranch, sha: baseSha } = await getDefaultBranchSha();
  const branchName = `securepulse/fix-${Date.now()}`;
  await createBranch(branchName, baseSha);

  const byFile = new Map();
  for (const finding of withPath) {
    const list = byFile.get(finding.file_path) || [];
    list.push(finding);
    byFile.set(finding.file_path, list);
  }


  const changedFiles = [];
  const skipped = [];
  for (const [filePath, fileFindings] of byFile) {
    try {
      const { content, sha } = await getFileContent(filePath, branchName);
      const fixedContent = await remediation.generateFileFix(filePath, content, fileFindings);
      if (fixedContent.trim() === content.trim()) {
        skipped.push({ filePath, reason: 'no change produced' });
        continue;
      }
      await updateFileContent(
        filePath,
        fixedContent,
        `fix: ${fileFindings.map((f) => f.title).join(', ')}`,
        sha,
        branchName
      );
      changedFiles.push({ filePath, findings: fileFindings });
    } catch (err) {
      skipped.push({ filePath, reason: err.message });
    }
  }

  if (changedFiles.length === 0) {
    const detail = skipped.map((s) => `${s.filePath} (${s.reason})`).join('; ');
    throw new Error(`Could not fix any of the queued findings: ${detail}`);
  }

  const title = `SecurePulse: fix ${withPath.length} finding${withPath.length === 1 ? '' : 's'}`;
  const body = [
    'Automated fix generated by SecurePulse from queued findings. Review carefully before merging.',
    '',
    ...changedFiles.map(
      ({ filePath, findings: fileFindings }) =>
        `**${filePath}**\n${fileFindings.map((f) => `- [${f.severity}] ${f.title}`).join('\n')}`
    ),
    ...(skipped.length > 0
      ? ['', '**Skipped** (could not be fixed automatically):', ...skipped.map((s) => `- ${s.filePath}: ${s.reason}`)]
      : []),
  ].join('\n');

  return openPullRequest(branchName, baseBranch, title, body);
}

module.exports = { createFixPullRequest };
