require('dotenv').config();
const express = require('express');
const cors = require('cors');
const scansRouter = require('./routes/scans');
const fixesRouter = require('./routes/fixes');
const app = express();
const PORT = process.env.PORT || 3001;
app.use(cors({ origin: ['http://localhost:3000', 'http://frontend:3000'], methods: ['GET', 'POST', 'DELETE', 'OPTIONS'] }));
app.use(express.json({ limit: '10mb' }));
app.get('/health', (req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString() }));
app.use('/api/scans', scansRouter);
app.use('/api/fixes', fixesRouter);
app.use((req, res) => res.status(404).json({ error: `Route ${req.method} ${req.path} not found` }));
app.use((err, req, res, next) => { console.error(err.stack); res.status(500).json({ error: 'Internal server error' }); });
app.listen(PORT, '0.0.0.0', () => { console.log(`SecurePulse backend running on port ${PORT}`); });
